export const youtubeSources: Record<string, string | null> = {
  "kaattrae-en-vaasal": "7paRB7j319c",
  "enna-solla-pogirai": "V2Jr0QyezrM",
  "kaadhal-kaditham": "kkrsSDRwpoE",
  "enakke-enakkaa": "tck__K8H3TE",
  "pachai-nirame": "HiocgIOIyik",
  "sotta-sotta": "B4-whCPWpxk",
  "yedho-ondru": "Fo-L7Q0tnBc",
  "mun-paniya": "B8WkcPTqQWE",
  "enna-vilai": "zwMEi4QBFrM",
  "nenjinile": "UKKEm8NraJQ",
  "nadhiyae-nadhiyae": "U1I4Aq0T4Kc",
  "poovukkul": "FWvZdFOv95Y",
  "poongatrile": "oY2Q4pVFQ3I",
  "azhagana-ratchasiye": "_GOfxJFdXsE",
  "kannoodu-kaanbathalam": "UtMUwHQ8Rz8",
  "melliname": "vngkmkAjbmQ",
  "kurukku-siruthavale": "Yy2lR7iYKRU",
  "anbae-anbae": "Vuxm2oXIEys",
  "kandukondain-kandukondain": "9r0WT8liWWc",
  "merke-merke": "_xcSfZV0TIE",
  "minnalai-pidithu": "LF_1_hy2wXU",
  "mudher-kanave": "oqttdELA8UM",
  "meghamai-vanthu-pogiren": "eY59PkEZLXk",
  "sarakku-vachiruken": "O-FiIR7JEDY",
  "vaadiamma": "0PASNC_-LEc",
  "enakkoru-snehidhi": "nqZ1hyvvFrQ",
  "june-july": "l7CJdZNQ0is",
  "thayya-thayya": "S4L879WD76o",
  "oru-ponnu-onnu": "FP5V0Kw6tvY",
  "ennavale-adi-ennavale": "conk9Etl_vE",
  "mukkala-mukkabla": "KudWfq2ldWE",
  "appadipodu": "i1BqRYMFS08",
  "ennavale-ennavale": "1Oo06M6SRKA",
  "sinthamani-sinthamani": "60OBuIgth5w",
  "asai-asai": "fw-bgvVZriA",
  "vaadi-vaadi-naattu-katta": null, // Needs verification - removed
  "varaaha-nadhi": null, // Needs verification - removed
  "oru-thuli": "8whO5b5Ggcw",
  "roja-roja": "tvwtUqtDt9I",
  "netru-illatha-maatram": "OBIIEy6tTa4",
  "penn-kiliye-penn-kiliye": "joh5ESbZcY4",
  "chudithar-aninthu": "Bngp-wKAdbc",
  "vaadi-vaadi": "d8DKbrYUbFA",
  "sivappu-lolakku": "bACkavgOxkg",
  "rosappu-chinna-rosappu": "uHXVZ2NKU1Y",
  "azhagana-chinna-devathai": "ECIOLPCJpek",
  "aagaasa-nilavu": null, // Metadata mismatch - removed
  "innisai-paadivarum": "GUdFE9yroCE",
  "columbus-columbus": "BtMOvr-EC9o",
  "oru-poiyavathu": "BkoYZfCnhSk",
  "nila-kaigiradhu": "KDa2fogQi04",
  "ennai-thalatta-varuvala": "y1ohtdkeHfQ",
  "mayilirage": "tCFbltjjfQA",
  "azhagooril": "PkCIBlYc2hw",
  "ale-ale": "w_7g1dx-GMo",
  "yenna-azhago": "Cu12FrlNA2w",
  "mottukkale": "awwF_Wut07g",
  "malare-oru-varthai": "Oxn5ZPiMmvg",
  "siruthooral": "pAJ3jBU_l1I",
  "pottu-vaitha-oru-vatta-nila": "7TR_7P8ZrD4",
  "raaja-raaja-chozhan": "VhKz3PF9iw4",
  "thendral-vandhu-theendum-pothu": "S9Jolu4ASxQ",
  "ilamai-ennum-poonkaatru": "M9CwgNNaNuM",
  "nilaave-vaa": "9km1rgLG8bw",
  "kanne-kalaimaane": "1JMz4f-Uhbo",
  "rasathi-unnai": "KTgScPRo5ow",
  "thenpandi-cheemayile": "mbai5NfwL3g",
  "kalyaana-thaen-nila": "_PSGe0KDmgE",
  "antha-vanatha": "ks41RJKMrIc",
  "malaiyoram-veesum-kaathu": "BgbafEuP8RE",
  "panivizhum-iravu": "-8v8gZaR09c",
  "ilaya-nila-pozhigirathe": "AsN_9uXAoNE",
  "sundari": "5R3_k3hJLfk",
  "valaiyosai": "730vCCxY_UI",
  "nila-adhu-vanathumele": "7dIrSI2fQ4c"
}

export function getVideoIdForTrack(trackId: string): string | null {
  return youtubeSources[trackId] || null
}
